### ISSUE TITLE
Erro ao executar o projeto

### ISSUE THREAD

**Issue by pablolopesk8** [viniciusrc15/node#1]
Ao rodar seu projeto, o seguinte erro é exibido:

TypeError: /Applications/XAMPP/xamppfiles/htdocs/vinicius/node/app/views/home/index.ejs:49
Cannot read property '0' of undefined

**Comment by viniciusrc15** [comment]
Este erro é decorrente da falta da estrutura do banco de dados que era local. Tratando-se de uma questão de trazer os dados do mesmo para a view, tentarei ver possibilidades de deixá-los estáticos.
